rt_public:
    resource: "@AppBundle/Controller/Common"
    type:     annotation
rt_account:
    resource: "@AppBundle/Controller/Account"
    type:     annotation


account_login_check:
    path: /account/login_check