# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
      rt.user.manager:
          class: AppBundle\Service\UserManager
          arguments:
              - '@security.encoder_factory'
      rt.sensor.manager:
              class: AppBundle\Service\SensorManager
              arguments:
                - '@doctrine.orm.entity_manager'